[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
js-sys = "0.3.70"
wasm-bindgen = "0.2.93"
web-sys = { version = "0.3.70", features = ["File", "Blob"] }

[lib]
crate-type = ["cdylib", "rlib"]


